### ISSUE TITLE
Box do Fedora/35-cloud-base para libvirt está com link quebrado

### ISSUE THREAD

**Issue by henmohr** [hector-vido/nicbr-ansible#1]
Olá!

Fui subir o vagrant com provider libvirt e verifiquei que o link para download está quebrado. 

Vou testar com [generic](https://app.vagrantup.com/generic)/[fedora36](https://app.vagrantup.com/generic/boxes/fedora36) e se der certo submito um PR.

**Comment by hector-vido** [comment]
Oi @henmohr!

Acabei esquecendo de vir responder, normalmente é algum tipo de problema do lado lá do Fedora.
Acho que esperando ele deve voltar sozinho mesmo.
